### ISSUE TITLE
Add templater for Prowjobs

### ISSUE THREAD

**Issue by abhay-krishna** [aws/eks-anywhere-prow-jobs#142]
Prowjobs should be templated so they can be configured easily based on a few parameters.

Refer to aws/eks-distro-prow-jobs#252 for implementation details.

**Comment by zafs23** [comment]
Initial PR has been made with main.go, Makefile and skeleton for presubmit prowjob yaml.

**Comment by zafs23** [comment]
EKS-D prow jobs have been updated in [this](https://github.com/aws/eks-distro-prow-jobs/pull/401) PR to be used in EKS-A prow jobs.

**Comment by zafs23** [comment]
Writing EKS-A prow job minimal config files

**Comment by zafs23** [comment]
Added new minimal configs and generated new prowjobs to the PR.

**Comment by zafs23** [comment]
Added additional jobs and minimal configs
